Comment "Elgato Wave XLR Pro"

SectionUseCase."HiFi" {
	Comment "Default"
	File "/USB-Audio/Elgato/Wave-XLR-Pro-HiFi.conf"
}

Include.dhw.File "/common/directm.conf"

Macro.0.DirectUseCase { Id="Direct" PlaybackChannels=17 CaptureChannels=18 }
Include.pcm_split.File "/common/pcm/split.conf"
